// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SlavinIgorkt_31_23.Database;

#nullable disable

namespace SlavinIgorKT_31_23.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20260913162840_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SlavinIgorkt_31_23.Models.Discipline", b =>
                {
                    b.Property<int>("DisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DisciplineId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Флаг удаления");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("name")
                        .HasComment("Название дисциплины");

                    b.HasKey("DisciplineId")
                        .HasName("pk_disciplines__discipline_id");

                    b.ToTable("disciplines", (string)null);
                });

            modelBuilder.Entity("SlavinIgorkt_31_23.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GradeId"));

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer")
                        .HasColumnName("discipline_id")
                        .HasComment("Идентификатор дисциплины");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id")
                        .HasComment("Идентификатор студента");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value")
                        .HasComment("Оценка");

                    b.HasKey("GradeId")
                        .HasName("pk_grades__grade_id");

                    b.HasIndex(new[] { "DisciplineId" }, "idx_grades_fk_discipline_id");

                    b.HasIndex(new[] { "StudentId" }, "idx_grades_fk_student_id");

                    b.ToTable("grades", (string)null);
                });

            modelBuilder.Entity("SlavinIgorkt_31_23.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroupId"));

                    b.Property<int>("Course")
                        .HasColumnType("integer")
                        .HasColumnName("course")
                        .HasComment("Курс обучения");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Флаг удаления");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("name")
                        .HasComment("Название группы");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("integer")
                        .HasColumnName("specialty_id")
                        .HasComment("Идентификатор специальности");

                    b.HasKey("GroupId")
                        .HasName("pk_groups__group_id");

                    b.HasIndex(new[] { "SpecialtyId" }, "idx_groups_fk_specialty_id");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("SlavinIgorkt_31_23.Models.Specialty", b =>
                {
                    b.Property<int>("SpecialtyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpecialtyId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("code")
                        .HasComment("Код специальности");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("title")
                        .HasComment("Название специальности");

                    b.HasKey("SpecialtyId")
                        .HasName("pk_specialtys__specialty_id");

                    b.ToTable("specialtys", (string)null);
                });

            modelBuilder.Entity("SlavinIgorkt_31_23.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("first_name")
                        .HasComment("Имя студента");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id")
                        .HasComment("Идентификатор группы");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Флаг удаления");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("last_name")
                        .HasComment("Фамилия студента");

                    b.HasKey("StudentId")
                        .HasName("pk_students__student_id");

                    b.HasIndex(new[] { "GroupId" }, "idx_students_fk_group_id");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("SlavinIgorkt_31_23.Models.Grade", b =>
                {
                    b.HasOne("SlavinIgorkt_31_23.Models.Discipline", "Discipline")
                        .WithMany()
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grades_discipline_id");

                    b.HasOne("SlavinIgorkt_31_23.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grades_student_id");

                    b.Navigation("Discipline");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SlavinIgorkt_31_23.Models.Group", b =>
                {
                    b.HasOne("SlavinIgorkt_31_23.Models.Specialty", "Specialty")
                        .WithMany()
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_groups_specialty_id");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("SlavinIgorkt_31_23.Models.Student", b =>
                {
                    b.HasOne("SlavinIgorkt_31_23.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_students_group_id");

                    b.Navigation("Group");
                });
#pragma warning restore 612, 618
        }
    }
}
